### ISSUE TITLE
All I get is empty response :(

### ISSUE THREAD

**Issue by dmagyar** [eehakkin/pam-ssh-auth-info#1]
Hi! First of, thank you for your module - I'm trying to use this to learn how to get SSH_AUTH_INFO_0 out of the env.
Unfortunately when I set "debug" on your module I get an empty result back:

```
Apr 28 11:01:06 ubuntutest authpriv.debug sshd: pam_ssh_auth_info(sshd:auth): empty SSH_AUTH_INFO_0
```
In /etc/pam.d/sshd I have only your module set as auth for testing:

```
auth       [success=ok]         pam_ssh_auth_info.so debug
```

And of course I have PAM and ChallengeResponseAuthentication enabled in sshd_config along with
```
AuthenticationMethods publickey:pam keyboard-interactive:pam
````

Any tips on why this is happening? 

Thanks,
Denes

**Comment by eehakkin** [comment]
> Hi! First of, thank you for your module

Thanks.

> I'm trying to use this to learn how to get SSH_AUTH_INFO_0 out of the env.
> Unfortunately when I set "debug" on your module I get an empty result back:
> 
> ```
> Apr 28 11:01:06 ubuntutest authpriv.debug sshd: pam_ssh_auth_info(sshd:auth): empty SSH_AUTH_INFO_0
> ```

That is actually expected. Empty SSH_AUTH_INFO_0 means that your SSH server supports SSH_AUTH_INFO_0 but none of the authentication methods have completed. The SSH_AUTH_INFO_0 consists of a list of **completed** authentication methods and public credentials (e.g. keys) used to authenticate the user but not the current not yet fully completed authentication method (`keyboard-interactive` in your case).

> In /etc/pam.d/sshd I have only your module set as auth for testing:
> 
> ```
> auth       [success=ok]         pam_ssh_auth_info.so debug
> ```

Look good (but please note that if you do not have account modules in /etc/pam.d/sshd then PAM reads the accounts modules from /etc/pam.d/other).

> And of course I have PAM and ChallengeResponseAuthentication enabled in sshd_config along with
> 
> ```
> AuthenticationMethods publickey:pam keyboard-interactive:pam
> ```

This is probably your problem.

Your first list of authentication method names is `publickey:pam`. I do not think that the SSH server supports public-key authentication using PAM (I haven't checked though how does it handle that) so that will always fail.

Your second list of authentication method names is `keyboard-interactive:pam` which allows keyboard-interactive authentication using PAM (but not using bsdauth). That seems sensible but it also means that during the PAM authentication there are no completed authentication methods.

You may want to use
```
AuthenticationMethods publickey,keyboard-interactive:pam
```
so that a remote user must first complete a public-key authentication and then a keyboard-interactive using PAM during which the public-key authentication is completed and thus the method name (`publickey`) along with the public credential (e.g. the SSH public key) is listed in SSH_AUTH_INFO_0.

> Any tips on why this is happening?

I hope this helps.
